# EdgeX GPS Device Service Configuration

[Writable]
LogLevel = "INFO"

[Writable.InsecureSecrets]
  [Writable.InsecureSecrets.DB]
  path = "redisdb"
    [Writable.InsecureSecrets.DB.Secrets]
    username = ""
    password = ""

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59999
ServerBindAddr = ""  # blank value defaults to Service.Host value
StartupMsg = "GPS Device Service started"
MaxRequestSize = 0 # Not currently used by SDK
RequestTimeout = "5s"
EnableNameFieldEscape = false

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Clients]
  [Clients.core-data]
  Protocol = "http"
  Host = "localhost"
  Port = 59880

  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

[MessageQueue]
Protocol = "redis"
Host = "localhost"
Port = 6379
Type = "redis"
AuthMode = "usernamepassword"  # required for redis messagebus (secure or insecure).
SecretName = "redisdb"
PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  [MessageQueue.Optional]
  # Default MQTT Specific options that need to be here to enable environment variable overrides of them
  # Client Identifiers
  ClientId = "device-gps"
  # Connection information
  Qos = "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
  KeepAlive = "10" # Seconds (must be 2 or greater)
  Retained = "false"
  AutoReconnect = "true"
  ConnectTimeout = "5" # Seconds
  SkipCertVerify = "false" # Only used if Cert/Key file or Cert/Key PEMblock are specified

[Database]
Type = "redisdb"
Host = "localhost"
Port = 6379
Timeout = "30s"

# Custom configuration for GPS Device Service
[GPSCustom]
SerialPort = "/dev/ttyUSB0"
BaudRate = 9600
ReadTimeout = "100ms"
Debug = true

[GPSCustom.Writable]
UpdateFrequency = "1s"
